### ISSUE TITLE
hyprland-devel: Missing headers error when trying to compile hyprland-plugins

### ISSUE THREAD

**Issue by aadi58002** [Makrennel/hyprland-void#39] opened 2024-03-10 17:48 UTC
When trying to compile https://github.com/hyprwm/hyprland-plugins -> hyprwinwrap.
I get the following missing headers error
```sh
hyprland-plugins/hyprwinwrap on  main took 3s ❯ make
g++ -shared -fPIC --no-gnu-unique main.cpp -o hyprwinwrap.so -g `pkg-config --cflags pixman-1 libdrm hyprland` -std=c++2b -O2
In file included from /usr/local/include/hyprland/src/includes.hpp:52,
                 from main.cpp:6:
/usr/local/include/hyprland/wlroots/wlr/types/wlr_layer_shell_v1.h:16:10: fatal error: wlr-layer-shell-unstable-v1-protocol.h: No such file or directory
   16 | #include "wlr-layer-shell-unstable-v1-protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:2: all] Error 1
```

BTW -> I already tried with hyprpm direct command and it just prints out missing headers error.

Waybar-hyprland-0.9.24_1
hypridle-0.1.1_1
hyprland-0.36.0_1
hyprland-devel-0.36.0_1
hyprland-protocols-0.2_1
hyprlock-0.1.0_1
hyprpaper-0.6.0_1
xdg-desktop-portal-hyprland-1.3.1_1

Hyprland packages
template -> https://github.com/aadi58002/void-packages/blob/master/srcpkgs/hyprland/template

**Comment by zmeyka3310** [comment] 2024-03-12 00:38
duplicate of #29

**Comment by Makrennel** [comment] 2024-03-15 21:56
Closing because duplicate. The error is useful though – it's expecting the headers to be in /usr/local (which is default if building from source), I wonder if a flag is needed to point towards /usr where it's installed with the package.

**Closed by Makrennel** 2024-03-15 21:56 UTC
