### ISSUE TITLE
Unresolvable shlib `libhyprlang.so`

### ISSUE THREAD

**Issue by FriederHannenheim** [Makrennel/hyprland-void#60] opened 2024-05-16 12:21 UTC
Got this error during install. Deleting and redownloading void-packages didn't help

xdg-desktop-portal-hyprland-1.3.1_1: broken, unresolvable shlib `libhyprlang.so'
Transaction aborted due to unresolved shlibs.

**Comment by Makrennel** [comment] 2024-05-16 14:27
Sounds like a duplicate of #48

**Closed** 2024-06-11 01:35 UTC
